﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Refit;
using __NAME__.Models.Diagnostics;
using __NAME__.Models.Examples;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace __NAME__.Api.Client.Diagnostics
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIDiagnosticsClient : IDiagnosticsClient
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIDiagnosticsClient(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<string> Ping()
        {
            var arguments = new object[] {  };
            return (Task<string>) methodImpls["Ping"](Client, arguments);
        }

        public virtual Task<IList<StatusItem>> ListStatus()
        {
            var arguments = new object[] {  };
            return (Task<IList<StatusItem>>) methodImpls["ListStatus"](Client, arguments);
        }

    }
}

namespace __NAME__.Api.Client.Examples
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIExampleClient : IExampleClient
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIExampleClient(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<IEnumerable<ExampleModel>> List()
        {
            var arguments = new object[] {  };
            return (Task<IEnumerable<ExampleModel>>) methodImpls["List"](Client, arguments);
        }

        public virtual Task<ExampleModel> Get(int id)
        {
            var arguments = new object[] { id };
            return (Task<ExampleModel>) methodImpls["Get"](Client, arguments);
        }

        public virtual Task<NewExampleCreatedModel> Create(NewExampleModel model)
        {
            var arguments = new object[] { model };
            return (Task<NewExampleCreatedModel>) methodImpls["Create"](Client, arguments);
        }

        public virtual Task Close(CloseExampleModel model)
        {
            var arguments = new object[] { model };
            return (Task) methodImpls["Close"](Client, arguments);
        }

        public virtual Task Delete(int id)
        {
            var arguments = new object[] { id };
            return (Task) methodImpls["Delete"](Client, arguments);
        }

    }
}


